// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aatzzynkzgqizcovsvpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdHp6eW5remdxaXpjb3ZzdnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzMyNDgsImV4cCI6MjA2MDMwOTI0OH0.E9zkaDVKPRUARS67AvItU-cC03qiuqen_whItO4NvuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);